version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  dashboard:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_BASE=http://api:8000
    depends_on:
      - api
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: >
      streamlit run frontend/dashboard.py
      --server.port 8501
      --server.address 0.0.0.0
      --server.headless true
      --server.enableCORS false
      --server.enableXsrfProtection false