services:
  - type: web
    name: leetcode-recommender-api
    env: python
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LEETCODE_SESSION
        sync: false
      - key: LEETCODE_USERNAME
        sync: false

  - type: web
    name: leetcode-recommender-dashboard
    env: python
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py \
     --server.port $PORT \
     --server.address 0.0.0.0 \
     --server.headless true \
     --server.enableCORS false \
     --server.enableXsrfProtection false
    envVars:
      - key: API_BASE
        sync: false